### ISSUE TITLE
npm ERR! 502 Bad Gateway - GET https://registry.npm.cmdjs.org/@emotion%2fcache

### ISSUE THREAD

**Issue by naveenrj98** [Aeolun/react-diff-viewer-continued#33] opened 2023-10-23 06:06 UTC
I am getting the below issue while installing this package, @Aeolun could you please help me here

npm ERR! 502 Bad Gateway - GET https://registry.npm.cmdjs.org/@emotion%2fcache 
my 
npm version: 8.11.0
node version: v16.15.1
react version: 16.13.1

**Comment by Aeolun** [comment] 2023-11-01 04:03
This looks more like an error caused by your package manager? There's not much I can do here I'm afraid.

**Comment by Aeolun** [comment] 2024-04-30 08:12
Closing this one, as I imagine it's not an issue any more.

**Closed by Aeolun** 2024-04-30 08:12 UTC
