### ISSUE TITLE
V3.3.1 cannot be used

### ISSUE THREAD

**Issue by moligit** [Aeolun/react-diff-viewer-continued#36] opened 2023-12-01 07:29 UTC
<img width="424" alt="image" src="https://github.com/Aeolun/react-diff-viewer-continued/assets/10444295/5672a346-e740-4911-ac0a-cf6ec2b64ebc">

version：3.3.1

**Comment by giovanni-bellini-argo** [comment] 2023-12-20 13:12
it works without problems on my project.
please add how to reproduce

**Comment by Aeolun** [comment] 2024-04-30 08:12
Can you try the latest `next` build? I think that might solve your issues. Please provide more information about how you've integrated this if not. Closing this one for now, since I can't really do anything with it.

**Closed by Aeolun** 2024-04-30 08:12 UTC
